config/routes.rb
Spirit::Press::Engine.routes.draw do
  resources :posts do
    collection do
      get :upcoming
      post :preview
    end
    member do
      put :publish
    end
  end
  namespace :admin do
    resources :posts
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  enum status: %i(upcoming published rejected)

  validates :slug, uniqueness: true, if: Proc.new { |post| post.slug.present? }
  validates :title, :summary, :body, presence: true

  counter :hits

  before_save :generate_summary
  before_create :generate_published_at
  before_validation :safe_slug

  def to_param
    self.slug.blank? ? self.id : self.slug
  end

  def self.find_by_slug!(slug)
    Post.find_by(slug: slug) || Post.find_by(id: slug) || raise(ActiveRecord::RecordNotFound.new(slug: slug))
  end

  def published_at
    super || self.updated_at
  end

  def published!
    self.update(published_at: Time.now)
    super
    if self.user_id
      Notification.create(notify_type: 'press_published',
                          user_id: self.user_id,
                          target: self)
    end
  end

  private

  def safe_slug
    self.slug.downcase!
    self.slug.gsub!(/[^a-z0-9]/i, '-')
  end

  def generate_published_at
    self.published_at = Time.now
  end

  def generate_summary
    if self.summary.blank?
      self.summary = self.body.split("\n").first(10).join("\n")
    end
  end
end

app/models/spirit/press/ability.rb
module Spirit::Press
  class Ability
    include CanCan::Ability

    attr_reader :user

    def initialize(u)
      @user = u
      if @user.blank?
        roles_for_anonymous
      elsif @user.roles?(:admin)
        can :manage, Post
      elsif @user.roles?(:super_admin)
        can :manage, Post
      elsif @user.roles?(:member)
        roles_for_members
      else
        roles_for_anonymous
      end
    end

    protected

    # 普通会员权限
    def roles_for_members
      can :create, Post
      can :update, Post, user_id: user.id, status: Post.statuses[:upcoming]
      can :destroy, Post, user_id: user.id, status: Post.statuses[:upcoming]
      basic_read_only
    end

    # 未登录用户权限
    def roles_for_anonymous
      cannot :manage, Post
      basic_read_only
    end

    def basic_read_only
      can [:read, :upcoming], Post
    end
  end
end

app/models/user/press_user_mixin.rb
class User
  module PressUserMixin
    extend ActiveSupport::Concern

    included do
      action_store :like, :post, counter_cache: true,class_name: 'Post'
    end
   
  end
end

app/controllers/spirit/press/admin/posts_controller.rb
module Spirit::Press::Admin
  class PostsController < ::Admin::ApplicationController
    layout '/layouts/admin'

    def index
      @posts = Post.includes(:user).order("id desc").page(params[:page])
    end

    def destroy
      @post = Post.find_by_slug!(params[:id])
      @post.destroy
      redirect_to admin_posts_path
    end
  end
end

app/controllers/spirit/press/application_controller.rb
module Spirit::Press
  class ApplicationController < ::ApplicationController
    helper Spirit::Press::ApplicationHelper

    def current_ability
      @current_ability ||= Spirit::Press::Ability.new(current_user)
    end
  end
end

app/controllers/spirit/press/posts_controller.rb
module Spirit::Press
  class PostsController < Spirit::Press::ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :update, :publish, :destroy]
    before_action :set_post, only: [:show, :edit, :update, :publish, :destroy]

    # GET /posts
    def index
      @posts = Post.includes(:user).published.order('published_at desc, id desc').page(params[:page]).per(10)
    end

    def upcoming
      @posts = Post.includes(:user).upcoming.order('id desc').page(params[:page]).per(10)
    end

    # GET /posts/1
    def show
      @post.hits.incr(1)
    end

    def preview
      out = Spirit::Markdown.call(params[:body])
      render plain: out
    end

    # GET /posts/new
    def new
      authorize! :create, Post
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
      authorize! :update, @post
    end

    # POST /posts
    def create
      authorize! :create, Post
      @post = Post.new(post_params)
      @post.user_id = current_user.id

      if @post.save
        redirect_to @post, notice: '文章提交成功，需要等待管理员审核。'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      authorize! :update, @post
      if @post.update(post_params)
        redirect_to @post, notice: '文章更新成功。'
      else
        render :edit
      end
    end

    def publish
      authorize! :publish, @post
      @post.published!
      redirect_to posts_path, notice: "文章审核成功。"
    end

    # DELETE /posts/1
    def destroy
      authorize! :destroy, @post
      @post.destroy
      redirect_to posts_url, notice: '文章删除成功。'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find_by_slug!(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :slug, :body, :summary)
      end
  end
end

app/helpers/spirit/press/application_helper.rb
module Spirit::Press
  module ApplicationHelper
    delegate :comments_path, to: :main_app

    def press_user_name_tag(user)
      return '官方' if user.admin?
      user_name_tag(user)
    end
  end
end

app/views/layouts/spirit/press/application.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag    "spirit/press/application", media: "all" %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "spirit/press/application" %>
<% end %>

<% content_for :main do %>
  <script type="text/javascript">
    $('.navbar-nav .nav-plugin-press').addClass("active");
  </script>
  <div id="spirit-press">
    <%= yield %>
  </div>
<% end %>

<%= render template: "/layouts/application" %>

app/views/notifications/_press_published.html.erb
<%
  post = notification.target
 %>
<% if post.blank? %>
  相关信息已删除
<% else %>
  <div class="media-heading">
    <p>你提交的文章《<%= link_to(post.title, spirit_press.post_path(post)) %>》已经审核通过。</p>
    <p>感谢支持，欢迎继续提交。</p>
  </div>
<% end %>

app/views/spirit/press/admin/posts/index.html.erb
<% content_for :sitemap do %>
  <span class="current"><%= t('plugin.press') %></span>
<% end %>

<table class="table table-bordered table-striped table-condensed">
<tr>
  <th>#</th>
  <th>状态</th>
  <th>标题</th>
  <th>提交人</th>
  <th>更新时间</th>
  <th style="width:100px"></th>
</tr>
<% @posts.each do |post| %>
<tr class="post">
  <td><%= post.id %></td>
  <td><%= post.status %></td>
  <td class="title"><%= link_to post.title, post %></td>
  <td class="author"><%= user_name_tag(post.user) %></td>
  <td class="time"><%= l post.updated_at, format: :long %></td>
  <td><%= link_to "", admin_post_path(post), 'data-confirm' => 'Are you sure?', method: :delete, class: "fa fa-trash" %></td>
</tr>
<% end %>
</table>

<%= paginate @posts %>

app/views/spirit/press/posts/_form.html.erb
<%= simple_form_for(post) do |f| %>
  <%= render "/shared/error_messages", target: post %>

  <%= f.input :title %>
  <%= f.input :slug %>
  <%= f.input :summary, as: :text %>

  <%= render "/shared/editor_toolbar" %>

  <div class="form-group">
    <%= f.text_area :body, class: 'spirit-editor form-control', input_html: { rows: 20 } %>
  </div>

  <div class="form-actions">
    <%= f.submit t("common.save"), class: "btn btn-primary col-xs-2", 'data-disable-with' => t("common.saving"), 'data-tb' => "save-press" %>
  </div>
<% end %>

app/views/spirit/press/posts/_post.html.erb
<div class="post media" id="post-<= post.id %>">
  <div class="media-left">
    <div class="post-likes<%= ' active' if post.likes_count >= 1 %>">
      <div class="icon"><i class="fa fa-heart"></i></div>
      <div class="counter"><%= post.likes_count %></div>
    </div>
  </div>
  <div class="media-body">
    <div class="post-title"><%= link_to post.title, post %></div>
    <% if post.published? %>
    <div class="post-summary markdown">
      <%= simple_format post.summary %>
    </div>
    <div class="post-info">
      <%= press_user_name_tag(post.user) %> ·
      <span class="time" title="发布时间"><i class="fa fa-clock-o"></i> <%= timeago(post.created_at) %></span> ·
      <%= link_to "#{post.comments_count} 条评论", post_path(post, anchor: 'comments') %>
    </div>
    <% end %>
  </div>
</div>

app/views/spirit/press/posts/_sidebar.html.erb
<div class="sidebar col-md-3 hide-ios">
  <div class="panel panel-default">
    <div class="panel-body">
      <% if can? :create, Post %>
        <%= link_to "提交新文章", new_post_path, class: 'btn btn-block btn-primary' %>
      <% end %>
      <hr />
      <%= link_to "RSS 订阅", posts_path(format: 'xml'), class: 'btn btn-block btn-default' %>

      <% if can? :publish, Post %>
      <hr />
      <a href="<%= upcoming_posts_path %>" data-turbolinks-action="replace">
        <i class="fa fa-newspaper-o"></i> 待审核列表...
      </a>
      <% end %>
    </div>
  </div>
  <%= raw Setting.spirit_index_sidebar_html %>
</div>

app/views/spirit/press/posts/edit.html.erb
<% title_tag "编辑文章" %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="heading">编辑文章</div>

    <%= render 'form', post: @post %>
  </div>
</div>

app/views/spirit/press/posts/index.html.erb
<% title_tag t('plugin.press') %>

<div class="row">
  <div class="col-md-9">
    <div id="post-list" class="panel panel-default post-<%= action_name %>">
      <div class="panel-body">
        <% if @posts.blank? %>
          <div class="no-result">暂无任何文章</div>
        <% else %>
          <%= render partial: 'post', collection: @posts %>
        <% end %>

        <%= paginate @posts %>
      </div>
    </div>
  </div>
  <%= render 'sidebar' %>
</div>

app/views/spirit/press/posts/new.html.erb
<% title_tag "提交新文章" %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="heading">提交新文章</div>

    <%= render 'form', post: @post %>
  </div>
</div>

app/views/spirit/press/posts/show.html.erb
<% title_tag @post.title %>

<div id="post-detail" class="panel panel-default">
  <div class="panel-body">
    <div class="post-opts clearfix">
      <div class="pull-left">
        <a href="<%= posts_path %>" class="btn btn-default"><i class="fa fa-chevron-left"></i> 返回文章列表</a>
      </div>

      <div class="pull-right">
        <% if can?(:update, @post) %>
        <%= link_to '编辑', edit_post_path, class: 'btn btn-sm btn-default' %>
        <% end %>

        <% if can?(:publish, @post) && @post.upcoming? %>
        <%= link_to '审核通过', publish_post_path, method: 'put', class: 'btn btn-sm btn-success' %>
        <% end %>

        <% if can?(:destroy, @post) && @post.upcoming? %>
        <%= link_to '删除', @post, method: 'delete', class: 'btn btn-sm btn-danger', data: { confirm: "确定要删除么？" } %>
        <% end %>
      </div>
    </div>
    <h1><%= @post.title %></h1>
    <div class="post-info">
      <%= press_user_name_tag(@post.user) %> ·
      <span class="time" title="发布时间"><i class="fa fa-clock-o"></i> <%= timeago @post.created_at %></span> ·
      <%= @post.hits.to_s %> 次阅读 ·
      <a href="#comments"><i class="fa fa-comments-o"></i> <%= @post.comments_count %> 条评论</a>
    </div>
    <div class="post-body markdown">
      <%= markdown @post.body %>
    </div>
    <%= social_share_button_tag @post.title %>
    <div class="post-actions">
      <%= likeable_tag(@post, class: 'btn btn-lg btn-default') %>

      <% unless @post.user&.admin? %>
        <%= reward_user_tag(@post.user, class: 'btn btn-lg btn-default') %>
      <% end %>
    </div>
  </div>
</div>

<div id="comments">
  <%= render "/shared/comments", commentable: @post %>
</div>

app/views/spirit/press/posts/upcoming.html.erb
<% title_tag t('plugin.press') %>

<div class="row">
  <div class="col-md-9">
    <div id="post-upcoming" class="panel panel-default post-<%= action_name %>">
      <div class="panel-heading">待审核列表</div>
      <div class="panel-body">
        <% if @posts.blank? %>
          <div class="no-result">暂无任何文章</div>
        <% else %>
          <table class="table table-bordered table-striped table-condensed">
            <tr>
              <th>#</th>
              <th>标题</th>
              <th>提交人</th>
              <th>更新时间</th>
            </tr>
            <% @posts.each do |post| %>
            <tr class="post">
              <td><%= post.id %></td>
              <td class="title"><%= link_to post.title, post %></td>
              <td class="author"><%= user_name_tag(post.user) %></td>
              <td class="time"><%= timeago post.updated_at %></td>
            </tr>
            <% end %>
          </table>
        <% end %>

        <%= paginate @posts %>
      </div>
    </div>
  </div>
  <%= render 'sidebar' %>
</div>